module.exports.build = require('./task/build')
module.exports.clean = require('./task/clean')
module.exports.init = require('./task/init')
module.exports.man = require('./task/man')
module.exports.path = require('./task/path')
module.exports.push = require('./task/push')
module.exports.stop = require('./task/stop')
module.exports.version = require('./task/version')